Repository javatastico/freshWarehouse, pull requests merged in 2022-08, with the labels that each got.

#10 Resolve 'Feature/ts01 create project models'
  .DS_Store
  .gitignore
  HELP.md
  freshWarehouse.iml
  mvnw
  mvnw.cmd
  pom.xml
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/meli/freshWarehouse/Documents/UML.png
  src/main/java/com/meli/freshWarehouse/FreshWarehouseApplication.java
  src/main/java/com/meli/freshWarehouse/controller/controller.java
  src/main/java/com/meli/freshWarehouse/dto/dto.java
  src/main/java/com/meli/freshWarehouse/exception/ExceededStock.java
  src/main/java/com/meli/freshWarehouse/exception/ExceptionDetails.java
  src/main/java/com/meli/freshWarehouse/exception/FileNotFoundException.java
  src/main/java/com/meli/freshWarehouse/exception/NotFoundException.java
  src/main/java/com/meli/freshWarehouse/handler/ExceptionHandler.java
  src/main/java/com/meli/freshWarehouse/model/Batch.java
  src/main/java/com/meli/freshWarehouse/model/Order.java
  src/main/java/com/meli/freshWarehouse/model/Product.java
  src/main/java/com/meli/freshWarehouse/model/Representative.java
  src/main/java/com/meli/freshWarehouse/model/Section.java
  src/main/java/com/meli/freshWarehouse/model/Seller.java
  src/main/java/com/meli/freshWarehouse/model/Warehouse.java
  src/main/java/com/meli/freshWarehouse/repository/repo.java
  src/main/java/com/meli/freshWarehouse/service/service.java
  src/main/resources/application-dev.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/test/java/com/meli/freshWarehouse/FreshWarehouseApplicationTests.java
  src/test/java/com/meli/freshWarehouse/controller/controller.java
  src/test/java/com/meli/freshWarehouse/integration/integration.java
  src/test/java/com/meli/freshWarehouse/repository/repository.java
  src/test/java/com/meli/freshWarehouse/service/service.java
  src/test/java/com/meli/freshWarehouse/util/util.java
Labels: technical issue

#12 Origin/feature/ts05 warehouse crud
  .DS_Store
  freshWarehouse.iml
  pom.xml
  src/main/java/com/meli/freshWarehouse/Documents/TS05-warehouse-crud.postman_collection.json
  src/main/java/com/meli/freshWarehouse/controller/WarehouseController.java
  src/main/java/com/meli/freshWarehouse/controller/controller.java
  src/main/java/com/meli/freshWarehouse/dto/WarehouseDTO.java
  src/main/java/com/meli/freshWarehouse/exception/WarehouseNotFoundException.java
  src/main/java/com/meli/freshWarehouse/handler/ExceptionHandlerController.java
  src/main/java/com/meli/freshWarehouse/model/Warehouse.java
  src/main/java/com/meli/freshWarehouse/repository/WarehouseRepo.java
  src/main/java/com/meli/freshWarehouse/repository/repo.java
  src/main/java/com/meli/freshWarehouse/service/IWarehouseService.java
  src/main/java/com/meli/freshWarehouse/service/WarehouseService.java
  src/main/java/com/meli/freshWarehouse/service/service.java
Labels: documentation

#32 Unit test for controller and service done
  Documents/collections/TS05-warehouse-crud.postman_collection.json
  src/main/java/com/meli/freshWarehouse/dto/ProductDTO.java
  src/main/java/com/meli/freshWarehouse/repository/BatchRepo.java
  src/main/java/com/meli/freshWarehouse/service/SectionService.java
  src/main/resources/application.properties
  src/test/java/com/meli/freshWarehouse/service/WarehouseServiceTest.java
  src/test/java/com/meli/freshWarehouse/util/GenerateProduct.java
  src/test/java/com/meli/freshWarehouse/util/GenerateWarehouse.java
Labels: test

#42 Update README.md
  README.md
Labels: documentation
